x-veld:
  chain:
    description: "Conversion of apis ner model data to harmonized custom json format."
    topic:
      - "ETL"
      - "Data Cleaning"

services:
  veld:
    build: ./code/
    command: python /veld/code/extract_and_clean.py
    volumes:
      - ./code/src/:/veld/code/
      - ./data/veld_data__apis_spacy_ner_legacy/:/veld/input/
      - ./data/veld_data__apis_oebl__ner_gold/data_uncleaned:/veld/output/uncleaned/
      - ./data/veld_data__apis_oebl__ner_gold/data_cleaned:/veld/output/cleaned/
      - ./data/veld_data__apis_oebl__ner_gold/data_cleaned_simplified:/veld/output/cleaned_simplified/
      - ./:/veld/output/log/
    environment:
      out_json_uncleaned_file: "uncleaned.json"
      out_json_cleaned_file: "cleaned.json"
      out_json_cleaned_simplified_file: "cleaned_simplified.json"
      out_log_file: "extract_and_clean.log"

